project:
  output-dir: rendered_quarto

toc: FALSE
number-sections: true

format:
  pdf:
    documentclass: scrartcl
    papersize: a4paper
    fontsize: '12'
    linestretch: 1.25
    indent: true
    fig-pos: 'H'
  docx:
    default
